# Generated by Django 3.1.2 on 2022-07-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('head0', models.CharField(default='', max_length=200)),
                ('chead0', models.TextField()),
                ('head1', models.CharField(default='', max_length=200)),
                ('chead1', models.TextField()),
                ('head2', models.CharField(default='', max_length=200)),
                ('chead2', models.TextField()),
                ('pub_date', models.DateField()),
                ('blog_image', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
