# Generated by Django 4.0.4 on 2022-06-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('emailid', models.EmailField(default='', max_length=150)),
                ('mobileno', models.IntegerField(default=0)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
