# Generated by Django 4.0.4 on 2022-06-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.TextField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('address', models.TextField()),
                ('mobileno', models.IntegerField(default=0)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zipcode', models.IntegerField(default='')),
                ('totalprice', models.IntegerField(default=0)),
            ],
        ),
    ]
